version: '2'

services:

  event-receiver:
    build: .
    environment:
      ABC: 'yes'
    volumes:
      - ./:/app
    networks:
      - code-network
    command: /app/run.sh rabbitmq 5672 guest guest events

  rabbitmq:
    image: rabbitmq:3.6.10
    networks:
      - code-network

networks:
    code-network:
        driver: bridge
